// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.util.HashMap;
import java.util.Map;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestN1 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\SeleniumChromeDriv\\chromedriver-win64\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testN1() throws InterruptedException {
    driver.get("https://langformula.ru/english-grammar/vremena-v-anglijskom-yazyke/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    //js.executeScript("window.scrollTo(0,116.80000305175781)");
    //driver.findElement(By.linkText("Словарь 3000")).click();
    //driver.findElement(By.linkText("Упражнения")).click();
    //driver.findElement(By.linkText("Уроки")).click();
    //driver.findElement(By.linkText("Аудирование")).click();
    WebDriverWait wait = new WebDriverWait(driver, 20); // Создаем объект WebDriverWait с таймаутом 10 секунд

//    WebElement dictionaryLink = wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//a[contains(text(), 'Словарь 3000')]")));
//    dictionaryLink.click();
//
//    // Замена на XPath для поиска элемента "Упражнения"
//    WebElement exercisesLink = wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//a[contains(text(), 'Упражнения')]")));
//    exercisesLink.click();
//
//// Замена на XPath для поиска элемента "Уроки"
//    WebElement lessonsLink = wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//a[contains(text(), 'Уроки')]")));
//    lessonsLink.click();
//
//// Замена на XPath для поиска элемента "Аудирование"
//    WebElement listeningLink = wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//a[contains(text(), 'Аудирование')]")));
//    listeningLink.click();
    WebElement dictionaryLink = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//a[contains(text(), 'Словарь 3000')]")));
    ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", dictionaryLink);
    wait.until(ExpectedConditions.elementToBeClickable(dictionaryLink)).click();

    // Прокрутка и клик по ссылке "Упражнения"
    WebElement exercisesLink = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//a[contains(text(), 'Упражнения')]")));
    ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", exercisesLink);
    wait.until(ExpectedConditions.elementToBeClickable(exercisesLink)).click();

    // Прокрутка и клик по ссылке "Уроки"
    WebElement lessonsLink = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//a[contains(text(), 'Уроки')]")));
    ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", lessonsLink);
    wait.until(ExpectedConditions.elementToBeClickable(lessonsLink)).click();

    // Прокрутка и клик по ссылке "Аудирование"
    WebElement listeningLink = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//a[contains(text(), 'Аудирование')]")));
    ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", listeningLink);
    wait.until(ExpectedConditions.elementToBeClickable(listeningLink)).click();

  }
}
